### Crear schema base (PUBLIC)
GET http://127.0.0.1:3000/tenants/create/base

### Crear tenant EMPRESA
POST http://127.0.0.1:3000/tenants/create/empresa
Content-Type: application/json

{
    "schema" : "Intel"
}


### Crear tenant SUCURSAL
POST http://127.0.0.1:3000/tenants/create/sucursal/e580df46-07da-484f-ba82-6bf6c93f6f14
Content-Type: application/json
x-tenant-id: public

{
    "schema" : "Mexico"
}




### Get all tenants empresa
GET http://127.0.0.1:3000/tenants/empresa
Content-Type: application/json
x-tenant-id: public

### Obtener empresa por id con sus sus sucursales
GET http://127.0.0.1:3000/tenants/empresa/e580df46-07da-484f-ba82-6bf6c93f6f14
x-tenant-id: public