### Crear schema base (PUBLIC)
GET http://127.0.0.1:3000/tenants/create/base

### Crear tenant EMPRESA
POST http://127.0.0.1:3000/tenants/create/empresa
Content-Type: application/json

{
    "schema" : "Motorola52"
}


### Crear tenant SUCURSAL
POST http://127.0.0.1:3000/tenants/create/sucursal/e8d77b0b-d3ee-4262-b617-1538671478d7
Content-Type: application/json
x-tenant-id: public

{
    "schema" : "Mexico"
}




### Get all tenants empresa
GET http://127.0.0.1:3000/tenants/empresa
Content-Type: application/json
x-tenant-id: public

### Obtener empresa por id con sus sus sucursales
GET http://127.0.0.1:3000/tenants/empresa/d58d894b-54c4-4752-921e-42915146e405
x-tenant-id: public