### Crear schema base (PUBLIC)
GET http://127.0.0.1:3000/tenants/create/base

### Crear tenant EMPRESA
POST http://127.0.0.1:3000/tenants/create/empresa
Content-Type: application/json
{
    "schema" : "Amd"
}


### Crear tenant SUCURSAL
POST http://127.0.0.1:3000/tenants/create/sucursal/1b96edea-aac9-4e00-8d8a-82e2d7ad3901
Content-Type: application/json
x-tenant-id: public

{
    "schema" : "sucursal matriz"
}




### Get all tenants empresa
GET http://127.0.0.1:3000/tenants/empresa
Content-Type: application/json
x-tenant-id: public


### Get all tenants sucursal by id empresa
GET http://127.0.0.1:3000/tenants/sucursal/1b96edea-aac9-4e00-8d8a-82e2d7ad3901
Content-Type: application/json
x-tenant-id: public




### Obtener clientes de un tenant especifico
GET http://127.0.0.1:3000/clientes
x-tenant-id : empresa_1b96edea_aac9_4e00_8d8a_82e2d7ad3901


### Guardar informacion en tenant especifico
POST  http://127.0.0.1:3000/clientes
x-tenant-id : empresa_1b96edea_aac9_4e00_8d8a_82e2d7ad3901
Content-Type: application/json

{
    "email" : "usuarioprueba4@gmail.com",
    "telefono" : "1258346592",
    "observacionCliente" : "ninguna prueba 4",
    "idOrganizacion" : "8a5856de-bbf5-4808-b755-b5e215036fae"
}


### Actualizar informacion por id de cliente en tenant espcifico
PUT http://127.0.0.1:3000/clientes/79a10a68-db86-4bd4-9d96-a94a050753d6
x-tenant-id : empresa_1b96edea_aac9_4e00_8d8a_82e2d7ad3901
Content-Type: application/json

{
    "email" : "usuarioupdate@gmail.com"
}