#Se obtienen la informacion del tenant enviado en el header

### Obtener clientes de un tenant especifico
GET http://127.0.0.1:3000/clientes/test1
x-tenant-id : empresa_e580df46_07da_484f_ba82_6bf6c93f6f14

###Test2
GET http://127.0.0.1:3000/clientes/test2
x-tenant-id : empresa_e580df46_07da_484f_ba82_6bf6c93f6f14

###Test3
GET http://127.0.0.1:3000/clientes/test3
x-tenant-id : empresa_e580df46_07da_484f_ba82_6bf6c93f6f14

###Test4
Get http://127.0.0.1:3000/clientes/Test4
x-tenant-id : empresa_e580df46_07da_484f_ba82_6bf6c93f6f14


### Guardar informacion en tenant especifico
#Se obtienen la informacion del tenant enviado en el header
POST  http://127.0.0.1:3000/clientes
x-tenant-id : empresa_e580df46_07da_484f_ba82_6bf6c93f6f14
Content-Type: application/json

{
    "email" : "user1@test.com",
    "telefono" : "1258346592",
    "observacionCliente" : "ninguna 1",
    "idOrganizacion" : "76e49ed8-361e-4e95-bba9-2fddb7599d41"
}


#Se obtienen la informacion del tenant enviado en el header
#El id del cliente es enviado por param
### Actualizar informacion por id de cliente en tenant espcifico
PUT http://127.0.0.1:3000/clientes/a890e2da-1886-47a1-988a-0d6efc1d1953
x-tenant-id : empresa_79a5dab6_0bf0_4a3d_a048_d8ce457fcc4f
Content-Type: application/json

{
    "email" : "actualizacion@gmail.com"
}


#Se obtienen la informacion del tenant enviado en el header
#El id del cliente es enviado por param
### Eliminar cliente por id en tenant especifico
DELETE http://127.0.0.1:3000/clientes/79a10a68-db86-4bd4-9d96-a94a050753d6
x-tenant-id : empresa_1b96edea_aac9_4e00_8d8a_82e2d7ad3901


### Guardar informacion en tenant especifico WRAP
#Se obtienen la informacion del tenant enviado en el header
POST  http://127.0.0.1:3000/clientes/wrap
x-tenant-id : empresa_e580df46_07da_484f_ba82_6bf6c93f6f14
Content-Type: application/json

{
    "email" : "user_wrap_5_wrap@test.com",
    "telefono" : "1258346592",
    "observacionCliente" : "ninguna en wrap",
    "idOrganizacion" : "76e49ed8-361e-4e95-bba9-2fddb7599d41"
}

### Actualizar informacion por id de cliente en tenant espcifico WRAP
#Se obtienen la informacion del tenant enviado en el header
#El id del cliente es enviado por param
PUT http://127.0.0.1:3000/clientes/wrap/d5111fea-c006-4d43-9cea-69fa7adbfa02
x-tenant-id : empresa_e580df46_07da_484f_ba82_6bf6c93f6f14
Content-Type: application/json

{
    "email" : "actualizacion_wrap_5.2@gmail.com"
}


### Eliminar cliente por id en tenant especifico WRAP
#Se obtienen la informacion del tenant enviado en el header
#El id del cliente es enviado por param
DELETE http://127.0.0.1:3000/clientes/wrap/d5111fea-c006-4d43-9cea-69fa7adbfa02
x-tenant-id : empresa_e580df46_07da_484f_ba82_6bf6c93f6f14