#Se obtienen la informacion del tenant enviado en el header

### Obtener clientes de un tenant especifico
GET http://127.0.0.1:3000/clientes
x-tenant-id : empresa_79a5dab6_0bf0_4a3d_a048_d8ce457fcc4f


### Guardar informacion en tenant especifico
#Se obtienen la informacion del tenant enviado en el header
POST  http://127.0.0.1:3000/clientes
x-tenant-id : empresa_79a5dab6_0bf0_4a3d_a048_d8ce457fcc4f
Content-Type: application/json

{
    "email" : "user2@test.com",
    "telefono" : "1258346592",
    "observacionCliente" : "ninguna 1",
    "idOrganizacion" : "110d8259-2500-4c23-9abe-0c76fbc22106"
}


#Se obtienen la informacion del tenant enviado en el header
#El id del cliente es enviado por param
### Actualizar informacion por id de cliente en tenant espcifico
PUT http://127.0.0.1:3000/clientes/a890e2da-1886-47a1-988a-0d6efc1d1953
x-tenant-id : empresa_79a5dab6_0bf0_4a3d_a048_d8ce457fcc4f
Content-Type: application/json

{
    "email" : "actualizacion@gmail.com"
}


#Se obtienen la informacion del tenant enviado en el header
#El id del cliente es enviado por param
### Eliminar cliente por id en tenant especifico
DELETE http://127.0.0.1:3000/clientes/79a10a68-db86-4bd4-9d96-a94a050753d6
x-tenant-id : empresa_1b96edea_aac9_4e00_8d8a_82e2d7ad3901